name: Publishing to Sonatype
on:
  release:
    types: [published]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Prepare gradle.properties
        run: |
          echo -e "${{ secrets.SECRING }}" | base64 -d > ./secring.gpg         
          echo "signing.keyId=${{ secrets.KEYID }}" >> ./gradle/wrapper/gradle-wrapper.properties
          echo "signing.password=${{ secrets.PASSWORD }}" >> ./gradle/wrapper/gradle-wrapper.properties
          echo "signing.secretKeyRingFile=./secring.gpg" >> ./gradle/wrapper/gradle-wrapper.properties
          echo "sonatypeUsername=${{ secrets.SUSER }}" >> ./gradle/wrapper/gradle-wrapper.properties
          echo "sonatypePassword=${{ secrets.SPASSWORD }}" >> ./gradle/wrapper/gradle-wrapper.properties
          cat ./gradle/wrapper/gradle-wrapper.properties
      - name: Prepare build.gradle
        run: |
          sed -i 's/.*sonatypeUsername.*/                username = "${{ secrets.SUSER }}"/' ./build.gradle
          sed -i 's/.*sonatypePassword.*/                password = "${{ secrets.SPASSWORD }}"/' ./build.gradle
      - name: Publish to Sonatype
        run: |
          cat ./build.gradle
          echo "OK"
          exit 0
          ./gradlew publishJarPublicationToStagingRepository
    